### ISSUE TITLE
eslint plugin does not pick configurations

### ISSUE THREAD

**Issue by andre-l-mm** [SublimeLinter/SublimeLinter-eslint#143] opened 2016-06-10 21:56 UTC
When running eslint from the command line it picks the settings properly. I tested using .eslintrc.yml, .eslintrc.json and settings in package.json eslintConfig node. 

In my eslint settings I have disabled or changed configuration of a few rules and I can see that reflected when I run from the command line. 

However, when I run from sublime it ignores my settings and presents a full list of issues as if I had not tweaked the configurations.
#### `SublimeLinter` console output

```
SublimeLinter: eslint: server.js ['C:\\projects\\gis\\git\\webservice-stubs\\node_modules\\.bin\\eslint.cmd', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
C:\projects\gis\git\webservice-stubs\server.js: line 1, col 46, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 2, col 37, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 3, col 58, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 4, col 1, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 5, col 46, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 6, col 48, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 7, col 32, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 8, col 36, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 9, col 56, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 10, col 1, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 11, col 22, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 12, col 17, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 13, col 27, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 14, col 1, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 15, col 70, Error - Expected linebreaks to be 'CRLF' but found 'LF'. (linebreak-style)
C:\projects\gis\git\webservice-stubs\server.js: line 16, col 2, Error - Newline required at end of file but not found. (eol-last)

16 problems 

```
#### `eslint` output from command line

```
$ ./node_modules/.bin/eslint.cmd --format compact server.js                     

C:\projects\gis\git\webservice-stubs\server.js: line 16, col 2, Error - Newline required at end of file but not found. (eol-last)
```
#### Additional info if needed (ST version, OS, configuration)

ST Version: 3, 
OS: Windows:
Configuration: 

```
{
    "extends": "google",
    "installedESLint": true,
    "rules": {
      "linebreak-style": [2,"windows"],
      "indent": [2,"tab"],
      "spaced-comment": [2,"never"],
      "one-var": [0]
    },
    "env": {
      "node": true,
      "mocha": true
    }
  }
```

**Comment by benmosher** [comment] 2016-06-13 08:35
What ESLint version are you using?

**Comment by andre-l-mm** [comment] 2016-06-14 11:46
Sorry for the delayed response. I was on vacations yesterday. This is what I get: 

$ eslint --version
v2.11.1

Thanks, 

Andre

**Comment by Nevitones** [comment] 2016-06-19 20:56
Hi @andre-l-mm,

I'm facing an issue and it seems similar to yours.
I believe that the only rule being ignored is the **linebreak-style**.

This is how I set my rule: 
``` javascript
"linebreak-style": [
	"error",
	"unix"
]
```
When I run the eslint from Sublime it doesn't show up any errors,
but when I run eslint from console it shows up linebreak errors for all lines.

I was thinking if it could by an issue with Sublime when it pipes the files to the eslint stdin.

**Comment by andre-l-mm** [comment] 2016-06-20 12:10
Hi Nevitones, 

Your issue is similar, basically a difference between Sublime and command line behavior. In my case the command line output is correct but the sublime output shows errors as if I had not tweaked the settings. All rules changed as described below are ignored in Sublime:

```
"rules": {
"linebreak-style": [
2,
"windows"
],
"indent": [
2,
"tab"
],
"spaced-comment": [
2,
"never"
],
"one-var": [
0
]
}
```

**Comment by andre-l-mm** [comment] 2016-06-20 12:42
Hi @Nevitones, 

Now if I set the rule to expect unix line endings then it passes on Sublime but fails on command line. This looks like a defect in Sublime or the sublime eslint plugin: "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style"

Issue is lower priority for me now because I can just use unix line endings on settings and Sublime will work, even though file is still saved with CRLF.

**Comment by Nevitones** [comment] 2016-06-20 14:35
Thanks for your attention @andre-l-mm,

I'm planning to use **eslint** with **gulp**, so I need it to work on both Sublime and Command line.

Lets wait for the two cents from other fellows ;)

**Comment by Nevitones** [comment] 2016-06-21 20:42
Hi fellows,

By spending some time adding print logs to a few **.py** files from the **SublimeLinter-eslint** and **SublimeLinter**, I confirmed that Sublime [normalizes](https://forum.sublimetext.com/t/all-line-endings-are-coverted-on-file-save/5507/4) the file line endings on memory.

Running the python lines below at the Sublime console, with a file using **Windows** line endings(CRLF) opened, I got:

``` python
view.line_endings()
# Returns 'Windows'

view.substr(sublime.Region(0, view.size())).find('\r\n')
# Returns -1 (No 'Windows' Line ending found at normalized file)
```

and with a file using **Mac OS** line endings(CR):

``` python
view.line_endings()
# Returns 'CR'

view.substr(sublime.Region(0, view.size())).find('\r\n')
# Returns -1 (No 'CR' Line ending found at normalized file)
```

So, no matter what line ending you set to the file on sublime, the files in memory will always have the **Unix** line ending('\n') and this is why we are facing the line ending lint issue.


I'll play a little more with python(that I've never had played with before) and try some workaround and maybe submit a pull request to the **SublimeLinter**.

*That's one small step for a Python Master, one giant leap for me!*

**Comment by Nevitones** [comment] 2016-06-22 04:05
Lets see what happens 
https://github.com/SublimeLinter/SublimeLinter3/pull/468

**Comment by jimbolla** [comment] 2016-08-10 15:54
Maybe SublimeLinter-eslint should just not run the linebreak-style rule, since it will always be LF, so the rule will always pass or always fail. Even better, if it sees that rule enabled, it should just configure Sublime to use the linebreak defined in the eslint rule.

**Comment by wal0x** [comment] 2017-05-03 14:22
Couldn't we change the setting of sublimeLinter-eslint so he serve the local file instead of the file in the memory created by sublime text ?

**Comment by RJSchmertz** [comment] 2017-05-24 14:13
This is unfortunate.  We use a .eslint file in source control so that every developer is following the same conventions.  But if this rule is turned on and set to windows line endings, all of your files are plastered with errors for line endings in Sublime.

**Comment by jackysee** [comment] 2017-06-12 01:59
+1 for having this issues. Have to turn off the `linebreak` rules for now...

**Comment by kaste** [comment] 2018-02-14 19:25
Closing, this is a feature of Sublime Text. We would need a really elegant and clever solution from the community here.

**Closed by kaste** 2018-02-14 19:25 UTC
