### ISSUE TITLE
Sublime console keeps popping open with the following ESLint couldn't find a configuration file error

### ISSUE THREAD

**Issue by mfbx9da4** [SublimeLinter/SublimeLinter-eslint#226] opened 2018-03-12 18:43 UTC
Just started happening. I shouldn't have to have a eslintrc for every project

![1t20jikrcw](https://user-images.githubusercontent.com/1690659/37303035-77abb4ec-25ea-11e8-9308-1a4fc2b53ec3.gif)

```
SublimeLinter: #18 eslint default.html ERROR:

 
Oops! Something went wrong! :(

ESLint couldn't find a configuration file. To set up a configuration file for this project, please run:

    eslint --init

ESLint looked for configuration files in /Users/da/code/mfbx9da4.github.io/_layouts and its ancestors.

If you think you already have a configuration file or if you need more help, please stop by the ESLint chat room: https://gitter.im/eslint/eslint
```

**Comment by rfearing** [comment] 2018-03-12 19:07
Same Issue

**Comment by kaste** [comment] 2018-03-12 19:14
Duplicate of #211

**Comment by kaste** [comment] 2018-03-14 09:47
Closing in favor of #211

**Closed by kaste** 2018-03-14 09:47 UTC
